#Updated Comment Property
#Sat Mar 22 06:17:03 IST 2025
password=Perigord2\!
browser=chrome
comment=GLAMS_cfDc
partnumber=BKT-16182-01
url=https\://glams6qa.glams.ie/Login?returnUrl\=%2FRequest%3FType%3DDefault%26taskName%3DDashboard
username=Hariprasad
